### ISSUE TITLE
Mac Catalyst sheet bug

### ISSUE THREAD

**Issue by sunsetsonwheels** [MAJKFL/Welcome-Sheet#1]
It looks like `.navigationViewStyle(.stack)` is required on Mac Catalyst, otherwise it will display in split view.

<img width="1180" alt="image" src="https://user-images.githubusercontent.com/35841468/150678421-f52e64f7-5024-46fc-8dad-f6294bd469e8.png">

**Comment by MAJKFL** [comment]
Thanks for the report! Fixed with the release `v0.1.1`.

**Comment by sunsetsonwheels** [comment]
Can confirm it's fixed. Thanks!
