### ISSUE TITLE
Ability to display local document

### ISSUE THREAD

**Issue by MatthewMerritt** [MAJKFL/Welcome-Sheet#3]
Your Welcome-Sheet looks awesome and works very well. I was wondering if you had any desire to add the ability to either display a document in a row or allow the button to open a local resource? My thought is for linking a local license file etc. I have an app that I would like to use your Welcome-Sheet, but the app has a requirement for working without any network/internet access and I want to have the ability to display a license from here.

**Comment by MAJKFL** [comment]
Hey, thanks for your kind words and suggestions! I've just added new branch with with two additional actions available for optional buttons: closures and custom views presented on top of Welcome Sheet. You set them as parameters during `WelcomeSheetPage` initialisation, just like you did with urls. I would suggest passing pdf view with your license to `optionalButtonView:` parameter when you create your page. After user taps the optional button it will be shown on screen.

```swift
WelcomeSheetPage(title: "Hello in my app!", rows: [
   // Rows
], optionalButtonTitle: "Terms and Conditions...", optionalButtonView: { DocumentView() })
```

I would love to hear your feedback and any new ideas. If everything works I will merge and make a release from it 🙂

**Comment by MatthewMerritt** [comment]
Hi! Yes this work exactly how I envisioned it! Thank you for integrating my idea. Sorry it took so long to get back to you I went out of town for a weekend concert...

I will see if I can come up with other ideas/use cases and pass them on.

Thanks,
Matt.

**Comment by MAJKFL** [comment]
Added with `v1.2.0`
