### ISSUE TITLE
Dark background for the welcome sheet

### ISSUE THREAD

**Issue by malhotrachetan** [MAJKFL/Welcome-Sheet#5]
Hey! Is there a way to turn the background from white to dark ?

**Comment by MAJKFL** [comment]
Thanks for suggestion! Just committed a way to do that. After the next release (which will hopefully materialise the next week) you'll just need to set that in your view modifier like this: `.welcomeSheet(isPresented: $showSheet, preferredColorScheme: .dark, pages: pages)`.

**Comment by MAJKFL** [comment]
Added with `v1.2.0`
